Traceback (most recent call last):
  File "<ipython-input-10-68e36b9cde7b>", line 7, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
